# startcode compose
version: "3.8"
services:

    rabbitmq:
        image: "rabbitmq:3.8-management"
        ports:
            - "15672:15672"
            - "5672:5672"
        healthcheck:
            test: ["CMD-SHELL", "if rabbitmqctl status; then \nexit 0 \nfi \nexit 1"]
            interval: 10s
            retries: 5
    swagger-ui:
       image: swaggerapi/swagger-ui
       container_name: swagger_ui_container
       ports:
          - "80:80"
       volumes:
          - ./doc:/usr/share/nginx/html/doc
       environment:
            API_URL: http://0.0.0.0:5062/swagger.json
    sql-data:
        image: "mcr.microsoft.com/mssql/server"
        #image: "microsoft/mssql-server-linux:latest"
        ports:
            - "1445:1433"
        container_name: mssqlcontainer
        environment:
            SA_PASSWORD: "p@ssw0rd"
            ACCEPT_EULA: "Y"
    bank.api:
        image: bank.api
        build:
            context: .
            dockerfile: ./src/Bank.API/Dockerfile
        ports:
            - "5062:80"
            - "7062:81"
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - NSBTransportHost=rabbitmq
            - MssqlConnectionString=Server=sql-data;Database=GringottsBankDb;User=sa;Password=p@ssw0rd
        depends_on:
            - rabbitmq
            - swagger-ui
            - sql-data
    bank.core.workerservice:
        image: bank.core.workerservice
        build:
            context: .
            dockerfile: ./src/Bank.CoreService/Bank.Core.WorkerServiceHost/Dockerfile
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - NSBTransportHost=rabbitmq
            - MssqlConnectionString=Server=sql-data;Database=GringottsBankDb;User=sa;Password=p@ssw0rd
        depends_on:
            - rabbitmq
            - sql-data

# endcode  